query BillsQuery($lang: String, $ids: [ID]) {
  bills(lang: $lang, ids: $ids) {
    id
    introducedDate
    sponsor {
      id
      congressRoles {
        startDate
        endDate
        congressNumbers
        state
      }
    }
  }
}
