query BillsQuery($lang: String, $ids: [ID]) {
  bills(lang: $lang, ids: $ids) {
    id
    introducedDate
    congress
    cosponsors {
      dateCosponsored
      member {
        id
        congressRoles {
          startDate
          endDate
          congressNumbers
          state
        }
      }
    }
  }
}
